title: RDF Lab

permaurl: /blog/:categories/:year/:month/:day/:title

collections:
  people:
    output: true

defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "person"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate


paginate: 10
paginate_path: "/blog/page:num/"
